language: node_js
node_js:
    - "6.10"

notifications:
    email: false

before_install: npm install -g grunt-cli
install: npm install
after_success: CODECLIMATE_REPO_TOKEN=7368a6efb80ff03de01019d31af5ecd0ae002900b6ce98c37ffbab9a82c0cd7d codeclimate < coverage/lcov.info
